### ISSUE TITLE
"Cannot read property 'map' of undefined" when running the code from "Basic Usage"

### ISSUE THREAD

**Issue by yajiex** [LIU9293/musicAPI#1]
Run the sample code from "Basic Usage", hit the following error:

    { success: false,
      message:
       TypeError: Cannot read property 'map' of undefined
           at NeteaseRequest.then.res (E:\Personal\PersonalWork\RaspberryPiMusicPlayer\node_modules\music-api\src\netease.js:48:40)
           at process._tickCallback (internal/process/next_tick.js:103:7) }

**Comment by LIU9293** [comment]
Hello, i tried again with basic usage example, it worked.
Can you confirm your server or PC is not behind any proxy ? It seems that you cannot connect to Netease's service. Maybe you can try to change 'netease' to 'xiami' or 'qq' and test again.
Another thing is **it's only possible to have this service in Chinese network**, if you do not live in China mainland, you will need to set up a proxy or a Cloud service like Aliyun.
I have a server running on Aliyun and i am developing a frontend website, maybe you can take a look at http://118.178.190.101/    .I tried it in Japan and xiami, qq is OK, but netease is not OK.

**Comment by yajiex** [comment]
Yep, try it without proxy and works like a charm, thanks!

**Comment by kslr** [comment]
@yajiex 

Overseas can also be in /etc/hosts IP

more: https://github.com/uku/Unblock-Youku/issues/488
