### ISSUE TITLE
如何单独书写 qq源查询?

### ISSUE THREAD

**Issue by Linbubin** [LIU9293/musicAPI#11]
你好， 我将您的qq源单独拿出来使用，没有经过总的MusicAPI进行查询
```
QQMusic.searchSong(query)
  .then(data => data.songList.map(x => ({
    icon: x.album.coverBig,
    title: x.name,
    subtitle: x.artists[0].name,
    track: {
        title: x.name,
        artist: x.artists[0].name,
        album: x.album.name,
        albumArt: x.album.coverBig,
        audio: QQMusic.getSong(x.id).then(song => song.url) // 这里
    }
  })
```

audio 如下
```
Promise {[[PromiseStatus]]: "resolved", 
        [[PromiseValue]]: "http://dl.stream.qqmusic.qq.com/M8000046HRBd0FvKLm…C380C8F140044403EDC0124&guid=489780640&fromtag=30"
        }
```

大致代码如上， 但是最后  track.audio的值为一个promise
我该如何取出其中的值？ 或者说 如何修改qq.js文件？？

**Comment by LIU9293** [comment]
Promise不是这样用的啊，`QQMusic.getSong(x.id).then(song => song.url)` 这里返回的是一个Promise，你现在的行为实际上是想找到一个列表，并且得到每一个文件的地址。

如果想得到一个列表里面的文件，你需要在获得这个歌曲的数组之后用Promise.all去查每一个地址，然后再包装到对应的数据里面。

实际上不建议直接去找歌曲的地址，因为地址可能是有加密和失效时间的，最好用到的时候再去查。

建议好好看看Promise的使用：[MDN Promise](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise)

**Comment by Linbubin** [comment]
不懂～    上面audio返回一个promise 可以直接对其进行操作，然后取出其中的 url吗？

**Comment by LIU9293** [comment]
@Linbubin 不可以，promise返回的是一个状态，在then里面还可以操作它的返回值，你把异步的方法当作同步去写，肯定不对的。
