### ISSUE TITLE
qq无法显示韩文

### ISSUE THREAD

**Issue by enzeberg** [LIU9293/musicAPI#17]
从虾米和网易获取的结果都能正常显示韩文，QQ音乐却不行。这应该是QQ的问题，不知道有没有办法解析那些数据（比如 &#45432;&#46972;&#51312;）。

**Comment by enzeberg** [comment]
GitHub真厉害，我把那些乱码粘过来，结果它们自动正常显示了。

**Comment by QiuShiqi** [comment]
QQ音乐接口的那个是Unicode编码，不是乱码来的。

**Comment by enzeberg** [comment]
qq音乐新版的api（[https://c.y.qq.com/soso/fcgi-bin/client_search_cp?](https://c.y.qq.com/soso/fcgi-bin/client_search_cp?)）貌似返回的韩文是正常的了。
